apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: podinfo
spec:
  interval: 5m
  #url: https://stefanprodan.github.io/podinfo
  url: https://github.com/stefanprodan/podinfo
